Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShoppingCart.Models;

namespace ShoppingCart.Controllers
{
    public class CartController : Controller
    {

        //get the database object for use in action methods
        private DBContext dbContext;
        public CartController(DBContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult ViewCart()
        {
            Session session = GetSession();
            //if (session == null)
            //    return RedirectToAction("Index", "Logout");

            //find the cart associated to the user
            if(session != null)
            {
                var CART = from c in dbContext.Carts
                           where c.User.Id == session.User.Id
                           select c;
                Cart cart = new Cart();
                foreach (var c in CART)
                {
                    cart = c;
                }
                ViewData["cart"] = cart;
                ViewData["DataBase"] = dbContext;

                //calculate the total price in cart
                float price = (float)Math.Round(CalculatePrice(cart), 1);
                ViewData["price"] = price;

                int cartitemqty = 0;

                foreach (CartItemCategory cc in cart.CartItemCategories)
                {
                    cartitemqty += cc.NumberOfItem;
                }

                string cartitemqtystring = cartitemqty.ToString();
                Response.Cookies.Append("cartitemqty", cartitemqtystring);
            }

            VisitorSession visitor = GetVisitorSession(); //VIEWING CART

            if(session == null && visitor != null)
            {
                var CART = from c in dbContext.Carts //Find Cart
                           where c.User.Id == visitor.User.Id
                           select c;


                    Cart cart = new Cart();
                
                ViewData["cart"] = cart;
                ViewData["DataBase"] = dbContext;

                //calculate the total price in cart
                float price = (float)Math.Round(CalculatePrice(cart), 1);
                ViewData["price"] = price;

                int cartitemqty = 0;

                foreach (CartItemCategory cc in cart.CartItemCategories)
                {
                    cartitemqty += cc.NumberOfItem;
                }

                string cartitemqtystring = cartitemqty.ToString();
                Response.Cookies.Append("cartitemqty", cartitemqtystring);
            }
            

            return View();
        }
        public IActionResult AddToCart([FromBody] ItemToCart items)
        {
            Session session = GetSession();
            if (session != null)
            {
                Cart cart = dbContext.Carts.FirstOrDefault(x => x.User.Id == session.User.Id);
                Guid Itemid = Guid.Parse(items.ItemId);

                CartItemCategory cartitems = dbContext.CartItemCategories.FirstOrDefault(x => x.Item.Id == Itemid);
                if (cartitems != null)
                {
                    cartitems.NumberOfItem += 1;
                }

                else
                {
                    Item item = dbContext.Items.FirstOrDefault(x => x.Id == Itemid);
                    CartItemCategory cartitemcategory = new CartItemCategory
                    {
                        NumberOfItem = 1,
                        Item = item,
                        Cart = cart
                    };
                    dbContext.CartItemCategories.Add(cartitemcategory);
                    cart.CartItemCategories.Add(cartitemcategory);


                }
                dbContext.SaveChanges();

                int cartitemqty = 0;

                foreach (CartItemCategory cc in cart.CartItemCategories)
                {
                    cartitemqty += cc.NumberOfItem;
                }

                string cartitemqtystring = cartitemqty.ToString();
                Response.Cookies.Append("cartitemqty", cartitemqtystring);
            }

            VisitorSession visitor = GetVisitorSession(); 

            if (session == null && visitor != null)
            {
                Cart cart = dbContext.Carts.FirstOrDefault(x => x.User.Id == visitor.User.Id);
                Guid Itemid = Guid.Parse(items.ItemId);

                CartItemCategory cartitems = dbContext.CartItemCategories.FirstOrDefault(x => x.Item.Id == Itemid);
                if (cartitems != null)
                {
                    cartitems.NumberOfItem += 1;
                }

                else
                {
                    Item item = dbContext.Items.FirstOrDefault(x => x.Id == Itemid);
                    CartItemCategory cartitemcategory = new CartItemCategory
                    {
                        NumberOfItem = 1,
                        Item = item,
                        Cart = cart
                    };
                    dbContext.CartItemCategories.Add(cartitemcategory);
                    cart.CartItemCategories.Add(cartitemcategory);


                }
                dbContext.SaveChanges();

                int cartitemqty = 0;

                foreach (CartItemCategory cc in cart.CartItemCategories)
                {
                    cartitemqty += cc.NumberOfItem;
                }

                string cartitemqtystring = cartitemqty.ToString();
                Response.Cookies.Append("cartitemqty", cartitemqtystring);
            }


            return Json(new { status = "success" });
        }
        
        public IActionResult ClearCart()
        {
            Session session = GetSession();
            if (session == null)
            {
                return Json(new { status = "fail" });
            }

            Response.Cookies.Delete("cartitemqty");
            return Json(new { status = "success" });
        }


        public IActionResult CheckOut()
        {
            Session session = GetSession();
            if(session==null)
                return RedirectToAction("Index", "Logout");

            Cart cart = dbContext.Carts.FirstOrDefault(x => x.User.Id == session.User.Id);
            //check if cart is empty
            bool empty = true;
            foreach(CartItemCategory ct in cart.CartItemCategories)
            {
                if (ct.NumberOfItem > 0)
                    empty = false;
            }
            if (empty == false)
            {
                Purchase purchase = new Purchase
                {
                    PurchaseDate = DateTime.Now,
                    PurchasedItems = new List<PurchasedItem>(),
                    Userid = cart.User.Id
                };
                dbContext.Add(purchase);
                foreach(CartItemCategory ct in cart.CartItemCategories)
                {
                    for(int i = 1; i <= ct.NumberOfItem; i++)
                    {
                        PurchasedItem purchasedItem = new PurchasedItem
                        {
                            ActivationKey = CreateActivationKey(),
                            ItemId = ct.Item.Id,
                            PurchaseId = purchase.Id
                        };
                        purchase.PurchasedItems.Add(purchasedItem);
                        dbContext.Add(purchasedItem);
                        dbContext.SaveChanges();
                    }
                }

                List<CartItemCategory> ccList = dbContext.CartItemCategories.Where(x => x.Cart.Id == cart.Id).ToList();
                foreach(CartItemCategory cc in ccList)
                {
                    dbContext.Remove(cc);
                    dbContext.SaveChanges();
                }
                cart.CartItemCategories = new List<CartItemCategory>();
                ClearCart();
            }

            return RedirectToAction("MyPurchases", "Purchases");
        }
        
        // for ADD and MINUS buttons in ViewCart page
        public IActionResult AdjustNum(string bookname, int quantity, int flag)
        {
            Session session = GetSession();
            if (session != null)
            {
                // retrieve the repective cart and cart-item-category
                Cart cart = dbContext.Carts.FirstOrDefault(x => x.User.Id == session.User.Id);
                CartItemCategory cc = dbContext.CartItemCategories.FirstOrDefault(x => x.Cart.Id == cart.Id && x.Item.Name == bookname.Trim());

                // ADD case, indicated by flag==1
                if (flag == 1)
                {
                    cc.NumberOfItem++;
                    dbContext.SaveChanges();

                }
                // MINUS case, indicated by flag!=1
                else
                {
                    cc.NumberOfItem--;
                    if (cc.NumberOfItem <= 0)
                        dbContext.Remove(cc);
                    dbContext.SaveChanges();
                }

                int cartitemqty = 0;

                foreach (CartItemCategory cc2 in cart.CartItemCategories)
                {
                    cartitemqty += cc2.NumberOfItem;
                }

                string cartitemqtystring = cartitemqty.ToString();
                Response.Cookies.Append("cartitemqty", cartitemqtystring);

            }


            VisitorSession visitor = GetVisitorSession();

            if (session == null && visitor != null)
            {
                Cart cart = dbContext.Carts.FirstOrDefault(x => x.User.Id == visitor.User.Id);
                CartItemCategory cc = dbContext.CartItemCategories.FirstOrDefault(x => x.Cart.Id == cart.Id && x.Item.Name == bookname.Trim());

                // ADD case, indicated by flag==1
                if (flag == 1)
                {
                    cc.NumberOfItem++;
                    dbContext.SaveChanges();

                }

Controllers/GalleryController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingCart.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingCart.Controllers
{
    public class GalleryController : Controller
    {
        private DBContext dbContext;

        public GalleryController(DBContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult AllProducts()
        {
            Session session = GetSession();
            if (session == null)
            {
                return RedirectToAction("Index", "Logout");
            }

            List<ShoppingCart.Models.Item> items = dbContext.Items.ToList();
            Dictionary<Guid, double> AvgItemScore = new Dictionary<Guid, double>();
            foreach (var itemID in items.Select(x => x.Id))
            {
                int[] scores = dbContext.Reviews.Where(x => x.ItemId == itemID).Select(x => x.Score).ToArray();
                double meanScore = (scores.Count() > 0) ? Math.Round(scores.Average(), 1) : 0.0;
                AvgItemScore.Add(itemID, meanScore);
            }
            ViewData["AvgItemScore"] = AvgItemScore;

            ViewData["items"] = items;

            return View();
        }

        public IActionResult Search(string searchStr)
        {
            if (searchStr == null)
            {
                return RedirectToAction("AllProducts");
            }

            List<Item> items = dbContext.Items.Where(x =>
                x.Name.Contains(searchStr) ||
                x.Description.Contains(searchStr)
            ).ToList();

            ViewData["searchStr"] = searchStr;
            ViewData["items"] = items;
            return View();
        }

        public JsonResult AutoComplete(string searchterm)
        {
            var products = (from items in dbContext.Items
                            where items.Name.Contains(searchterm)
                            select new
                            {
                                label = items.Name,
                                val = items.Id
                            }).ToList();

            return Json(products);
        }

        private Session GetSession()
        {
            if (Request.Cookies["SessionId"] == null)
            {
                return null;
            }

            Guid sessionId = Guid.Parse(Request.Cookies["SessionId"]);// checking for the cookie,
                                                                      // extract session and pass back
            Session session = dbContext.Sessions.FirstOrDefault(x =>
                x.Id == sessionId
            );

            return session;//to use user information
        }


    }
}

Views/Shared/_Layout.cshtml
@section Scripts {
    <script src="~/js/Gallery/Gallery.js"></script>
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Shopping @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/List.css" />
    <script src="//cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="//cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            @if (Context.Request.Cookies["SessionId"] != null)
            {
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Gallery" asp-action="AllProducts" style="font-weight:bold">Hello, @Context.Request.Cookies["Username"]!</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" id=" select_count_box">
                        <p id="select_count" class="nav navbar-text navbar-right">
                            <a class="fa fa-shopping-cart" asp-area="" asp-controller="Cart" asp-action="ViewCart" aria-hidden="true" style="float: left; font-size: 20pt; margin-right: 10px;"></a> @Context.Request.Cookies["cartitemqty"]
                        </p>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="" asp-controller="Purchases" asp-action="MyPurchases" style="margin-top:9px;text-decoration:underline;color:steelblue">My Purchases</a>
                            </li>
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="" asp-controller="Logout" asp-action="Index" style="margin-top: 9px; text-decoration: underline;color:steelblue">Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>
            }
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
            </a>
            <span class="text-muted">© SA53 Team 6 Shopping Cart</span>
        </div>
    </footer>
</div>